  version: '2'
  
  networks:
      demo:
  
  volumes:
    redis-data:
      driver: local
  
 services:
 
     lb:
         image: nginx
         container_name: lb
         volumes:
             - ./containers/nginx/proxy-pass.conf:/etc/nginx/nginx.conf
         networks:
             - demo
         ports:
             - "80:80"
 
     web:
         build: ./containers/web
         image: grazielevasconcelos/flask-lb-demo
         volumes:
             - ./src:/app
         expose:
             - "80"
         networks:
             demo:
                 aliases:
                     - backendapps
     redis:
         image: redis
         container_name: cache
         volumes:
             - redis-data:/data
         ports:
             - "6379:6379"
         command: ["redis-server", "--appendonly", "yes"]
 
         networks:
             - demo
